modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://discord.gg/uDfJQ4PSXc"

[[mods]]
modId="loyellowhills"
version="${file.jarVersion}"
displayName="Legend of the Yellow Hills"
logoFile="logo.png"
credits="VMFix, Pandorius_Fox"
authors="neros2k, Faradey ( Yellow Fire )"
description='''
Легенды гласят, что в гущах темных лесов скрывается холмистая местность с желто-персиковыми деревьями!
Отправляйтесь туда и раскройте все тайны телдерских руин, освой магию, победи Экстратарского голема и стань новым правителем Телдера!
'''

[[dependencies.loyellowhills]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.loyellowhills]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
